### ISSUE TITLE
Command failed with exit code 1

### ISSUE THREAD

**Issue by snuggs** [sveltejs/svelte-bench#8]
Followed the steps.

Failed at `yarn` step.
![capture d ecran 2017-05-10 a 20 02 40](https://cloud.githubusercontent.com/assets/38223/25926193/bed281a4-35bb-11e7-87a3-d5c8234c426b.png)

**Comment by PaulBGD** [comment]
You'll probably want a newer version of Node, I think 4 works but I run 7.

**Comment by snuggs** [comment]
yeah i got it @PaulBGD. Thanks for the heads up. nvm issue. 

![image](https://cloud.githubusercontent.com/assets/38223/26090003/f9c14f08-39cf-11e7-90b6-6e91d9281dad.png)
